# Generated by Django 6.0 on 2025-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
