# Generated by Django 6.0 on 2025-12-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_student_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='message',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='age',
        ),
    ]
